[package]
name = "wedp"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = "2.33"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.9.17"
mockall = "0.11.3"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
mockall = "0.11.3"
