# Instruction + template repo: https://github.com/FedericoPonzi/rust-ci
name: cross-build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: deploy
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - os: ubuntu-latest
            target: i686-unknown-linux-musl
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabi
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os: macOS-latest
            target: aarch64-apple-darwin
          - os: macOS-latest
            target: x86_64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.config.target }}

      - name: Build target
        if: matrix.config.os == 'ubuntu-latest'
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.config.target }} --manifest-path ./Cargo.toml

      - name: Build Apple targets
        if: matrix.config.os == 'macOS-latest'
        shell: bash
        run: |
          rustup target add aarch64-apple-darwin
          cargo build --release --target ${{ matrix.config.target }} --manifest-path ./Cargo.toml

      - name: Package
        shell: bash
        run: |
          #strip target/${{ matrix.config.target }}/release/wedp     
          tar -czvf ./-${{ matrix.config.target }}.tar.gz -C /target/${{ matrix.config.target }}/release/wedp
      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
          files: "wedp*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
