name: Rust Cross-Compile and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Cross-Compile and Release
    # runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust and cross
        run: |
          docker pull rustembedded/cross:aarch64-unknown-linux-gnu
          docker pull rustembedded/cross:x86_64-unknown-linux-gnu
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install cross

      - name: Install M1 toolchain
        if: runner.os == 'macos'
        run: rustup target add aarch64-apple-darwin

      - name: Determine the current version
        id: get_version
        run: echo "::set-output name=version::$(cat Cargo.toml | grep version | head -n1 | cut -d '\"' -f2)"

      - name: Increment the version number
        id: increment_version
        run: |
          IFS='.' read -r -a version_array <<< "${{ steps.get_version.outputs.version }}"
          (( version_array[1] += 1 ))
          new_version="${version_array[0]}.${version_array[1]}.0"
          echo "::set-output name=new_version::$new_version"

      - name: Cross-compile for Linux x86_64
        run: cross build --release --target x86_64-unknown-linux-gnu
      - name: Cross-compile for Linux ARMv7
        run: cross build --release --target armv7-unknown-linux-gnueabihf
      - name: Cross-compile for macOS x86_64
        run: cross build --release --target x86_64-apple-darwin
      - name: Cross-compile for macOS ARM64
        if: runner.os == 'macos'
        run: cross build --release --target aarch64-apple-darwin

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/myapp
            target/armv7-unknown-linux-gnueabihf/release/myapp
            target/x86_64-apple-darwin/release/myapp
            target/aarch64-apple-darwin/release/myapp
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.increment_version.outputs.new_version }}
          target_commitish: ${{ github.sha }}
          name: v${{ steps.increment_version.outputs.new_version }}
          body: Release v${{ steps.increment_version.outputs.new_version }}
