name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_BACKTRACE: full
  CRATE_NAME: wedp

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install cross
      run: cargo install cross

    - name: Cross-compile for Linux
      run: cross build --release --target x86_64-unknown-linux-gnu
      env:
        BUILD_VERSION: ${{ github.ref }}
        OUTPUT_DIR: ./target/x86_64-unknown-linux-gnu/release
        PLATFORM: linux-x64

    - name: Cross-compile for ARMv7
      run: cross build --release --target armv7-unknown-linux-gnueabihf
      env:
        BUILD_VERSION: ${{ github.ref }}
        OUTPUT_DIR: ./target/armv7-unknown-linux-gnueabihf/release
        PLATFORM: linux-armv7

    - name: Cross-compile for ARM64
      run: cross build --release --target aarch64-unknown-linux-gnu
      env:
        BUILD_VERSION: ${{ github.ref }}
        OUTPUT_DIR: ./target/aarch64-unknown-linux-gnu/release
        PLATFORM: linux-arm64

    - name: Cross-compile for macOS Intel
      run: cross build --release --target x86_64-apple-darwin
      env:
        BUILD_VERSION: ${{ github.ref }}
        OUTPUT_DIR: ./target/x86_64-apple-darwin/release
        PLATFORM: mac-x64

    - name: Cross-compile for macOS M1
      run: cross build --release --target aarch64-apple-darwin
      env:
        BUILD_VERSION: ${{ github.ref }}
        OUTPUT_DIR: ./target/aarch64-apple-darwin/release
        PLATFORM: mac-arm64

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: |
          Changes in this Release:
          - Add feature A
          - Fix bug B
          - Improve performance C
        draft: false
        prerelease: false

    - name: Upload Linux Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.OUTPUT_DIR }}/${{ env.CRATE_NAME }}
        asset_name: ${CRATE_NAME}-${{ env.VERSION }}-${{ env.PLATFORM }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload macOS Intel Asset
      uses: actions/upload-release-asset@v1
      if: contains(env.PLATFORM, 'mac-x64')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url
